@startuml
actor Kunde
actor Buchungssystem
database Datenbank

Kunde -> Buchungssystem: Tische anzeigen für gewünschten Termin
activate Buchungssystem
Buchungssystem --> Kunde: Liste der verfügbaren Tische
Kunde -> Buchungssystem: Tische reservieren für gewünschten Termin
Buchungssystem -> Datenbank: Überprüfe Tischverfügbarkeit
activate Datenbank
Datenbank --> Buchungssystem: Tischverfügbarkeit bestätigt
deactivate Datenbank
Buchungssystem --> Kunde: Bestätigung der Reservierung
Kunde -> Buchungssystem: Reservierung ggf. stornieren
Buchungssystem -> Datenbank: Storniere Reservierung
activate Datenbank
Datenbank --> Buchungssystem: Stornierung bestätigt
deactivate Datenbank
Buchungssystem --> Kunde: Bestätigung der Stornierung
Kunde -> Buchungssystem: Logout

deactivate Buchungssystem

@enduml
